print('Ce nume si prenume ai?')
np=str(input('Introdu numele si prenumele:'))
print(np)
print('Ce iti doresti sa devii in viitor?')
pr=str(input('Inrodu o profesie:'))
print(pr)
print('Te numesti',np)
print('Doresti sa devii',pr)